### ISSUE TITLE
Before we pull this into IBM Connections Cloud...

### ISSUE THREAD

**Issue by ibmcndev** [leonjuan/time2demo-customizer-dev#1]
1. Could you rename the repo to something that gives an indication of what it is (even if that is purely for experiments ;-))
2. Add a little more content, even some info about what is intended in the repo would be good

**Comment by leonjuan** [comment]
Hi, just renamed the repo to time2demo-customizer-dev and added info to my readme, this is my developer repo for using with my presales connections cloud demo account (1000244359).
Please let me know if you need me to add anything else, i have no code created yet but i will start testing later this week.

Thanks.
